import { Output, type UIMessage, generateText } from 'ai';
import { z } from 'zod';

import { getModel } from '@/lib/ai/model';
import type { Locale } from '@/lib/i18n/locale';
import type { Syllabus } from '@/lib/syllabus/schema';

const bootstrapInstructions: Record<Locale, string> = {
  en: `You are generating metadata to initialise a new learning journey.

Given the chat transcript and syllabus draft below, output:
- title: A short, specific title for the journey (3–10 words). Reflect the actual topic and scope agreed upon — do not invent content that was not discussed.
- memory: An array of concise learner insights drawn from the conversation. Each entry is one sentence written in the second person ("You want to…", "You already know…"). Include: stated goals, prior knowledge, gaps, pace preferences, and any other relevant context. Omit entries where nothing meaningful was said. Return an empty array if nothing is known.`,
  fr: `Vous générez les métadonnées pour initialiser un nouveau parcours d'apprentissage.

À partir de la transcription du dialogue et du brouillon du syllabus ci-dessous, produisez :
- title : Un titre court et précis pour le parcours (3 à 10 mots). Reflétez le sujet et la portée réellement convenus — n'inventez pas de contenu qui n'a pas été discuté.
- memory : Un tableau d'informations concises sur l'apprenant tirées de la conversation. Chaque entrée est une phrase rédigée à la deuxième personne (« Vous souhaitez… », « Vous savez déjà… »). Incluez : objectifs déclarés, connaissances préalables, lacunes, préférences de rythme et tout autre contexte pertinent. Omettez les entrées pour lesquelles rien de significatif n'a été dit. Renvoyez un tableau vide si rien n'est connu.`,
};

const bootstrapSchema = z.object({
  title: z.string().min(3).max(80),
  memory: z.array(z.string()),
});

/** Input for bootstrapping a new journey from a completed syllabus chat. */
export type BootstrapJourneyInput = {
  /** The finalized syllabus draft. */
  draft: Syllabus;
  /** Full chat transcript used to infer title and learner context. */
  messages: UIMessage[];
  /** Locale for the LLM instructions. */
  locale: Locale;
};

/** Data generated by the bootstrap step before persisting a journey. */
export type BootstrapResult = {
  /** Short, specific title for the journey (3–10 words). */
  title: string;
  /** Ordered list of learner insights written in the second person. */
  memory: string[];
};

/**
 * Calls the LLM to derive a journey title and learner memory from
 * the chat transcript and syllabus draft.
 *
 * @param input - Syllabus, message history, and locale.
 * @returns Generated title and learner memory.
 */
export async function bootstrapJourney({
  draft,
  messages,
  locale,
}: BootstrapJourneyInput): Promise<BootstrapResult> {
  const transcript = messages
    .map((m) => {
      const text = m.parts
        .filter((p) => p.type === 'text')
        .map((p) => p.text)
        .join(' ');
      return `${m.role}: ${text}`;
    })
    .join('\n');

  const { output } = await generateText({
    model: getModel(),
    prompt: `${bootstrapInstructions[locale]}\n\nChat transcript:\n${transcript}\n\nSyllabus draft:\n${JSON.stringify(draft, null, 2)}`,
    output: Output.object({ schema: bootstrapSchema }),
  });

  return output;
}
